name: Publish daily fortune

on:
  workflow_dispatch:

jobs:
  fortune:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: |
          docker pull ghcr.io/wivik/fortune:latest

      - name: Generate fortune
        run: |
          mkdir output
          chmod 777 output
          docker run --rm -v ${{ github.workspace }}/output:/fortune/output ghcr.io/wivik/fortune:latest -w https://fortune.zedas.fr

      - run: find .
        

